
import java.awt.event.WindowEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gresh
 */
public class Admin_Main extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Main
     */
    public Admin_Main() {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_add_show = new javax.swing.JButton();
        jButton_logout = new javax.swing.JButton();
        jButton_view_visitors = new javax.swing.JButton();
        text_atlanta_zoo3 = new java.awt.Label();
        jButton_view_staff = new javax.swing.JButton();
        jButton_view_shows = new javax.swing.JButton();
        jButton_view_animals = new javax.swing.JButton();
        jButton_add_animal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jButton_add_show.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_add_show.setText("Add Show");
        jButton_add_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_add_showMouseClicked(evt);
            }
        });
        jButton_add_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_showActionPerformed(evt);
            }
        });

        jButton_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_logout.setText("Logout");
        jButton_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_logoutMouseClicked(evt);
            }
        });
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        jButton_view_visitors.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_view_visitors.setText("View Visitors");
        jButton_view_visitors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_view_visitorsMouseClicked(evt);
            }
        });
        jButton_view_visitors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_view_visitorsActionPerformed(evt);
            }
        });

        text_atlanta_zoo3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        text_atlanta_zoo3.setName(""); // NOI18N
        text_atlanta_zoo3.setText("Atlanta Zoo");

        jButton_view_staff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_view_staff.setText("View Staff");
        jButton_view_staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_view_staffMouseClicked(evt);
            }
        });

        jButton_view_shows.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_view_shows.setText("View Shows");
        jButton_view_shows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_view_showsMouseClicked(evt);
            }
        });
        jButton_view_shows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_view_showsActionPerformed(evt);
            }
        });

        jButton_view_animals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_view_animals.setText("View Animals");
        jButton_view_animals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_view_animalsMouseClicked(evt);
            }
        });
        jButton_view_animals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_view_animalsActionPerformed(evt);
            }
        });

        jButton_add_animal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_add_animal.setText("Add Animal");
        jButton_add_animal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_add_animalMouseClicked(evt);
            }
        });
        jButton_add_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_animalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_view_visitors)
                    .addComponent(jButton_view_shows)
                    .addComponent(jButton_add_show))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_add_animal)
                    .addComponent(jButton_view_staff)
                    .addComponent(jButton_view_animals)
                    .addComponent(jButton_logout))
                .addContainerGap(222, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(text_atlanta_zoo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_atlanta_zoo3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_view_visitors)
                    .addComponent(jButton_view_staff))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_view_shows)
                    .addComponent(jButton_view_animals))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add_show)
                    .addComponent(jButton_add_animal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton_logout)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_add_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_showActionPerformed
        Admin_Add_Shows ex = new Admin_Add_Shows();
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_add_showActionPerformed

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_logoutActionPerformed

    private void jButton_view_visitorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_view_visitorsActionPerformed
        Admin_View_Visitors ex = new Admin_View_Visitors();
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_view_visitorsActionPerformed

    private void jButton_view_showsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_view_showsActionPerformed
        Admin_Search_For_Shows ex = new Admin_Search_For_Shows();
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_view_showsActionPerformed

    private void jButton_view_animalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_view_animalsActionPerformed
        Admin_Search_For_Animals ex = new Admin_Search_For_Animals();
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_view_animalsActionPerformed

    private void jButton_view_visitorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_view_visitorsMouseClicked

    }//GEN-LAST:event_jButton_view_visitorsMouseClicked

    private void jButton_view_staffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_view_staffMouseClicked
        Admin_View_Staff ex = new Admin_View_Staff();
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_view_staffMouseClicked

    private void jButton_view_showsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_view_showsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_view_showsMouseClicked

    private void jButton_view_animalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_view_animalsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_view_animalsMouseClicked

    private void jButton_add_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_add_showMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_add_showMouseClicked

    private void jButton_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_logoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_logoutMouseClicked

    private void jButton_add_animalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_add_animalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_add_animalMouseClicked

    private void jButton_add_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_animalActionPerformed
        Admin_Add_Animal ex = new Admin_Add_Animal();
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_add_animalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add_animal;
    private javax.swing.JButton jButton_add_show;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_view_animals;
    private javax.swing.JButton jButton_view_shows;
    private javax.swing.JButton jButton_view_staff;
    private javax.swing.JButton jButton_view_visitors;
    private java.awt.Label text_atlanta_zoo3;
    // End of variables declaration//GEN-END:variables
}
