
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gresh
 */
public class Admin_View_Staff extends javax.swing.JFrame {

    /**
     * Creates new form ViewStaff
     */
    public Admin_View_Staff() {
        initComponents();
        fillValues();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    
    public void fillValues() {
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
            "cs4400_group8",
            "l5sU95me");
            PreparedStatement stmt = null;
            String sql = "select * from Users where Role = ?";
            stmt = con.prepareStatement(sql);
            stmt.setString(1, "Staff");
            ResultSet rs = stmt.executeQuery();
            int i = 0;
            String value;
            while (rs.next()) {
                for (int j = 0; j < 2; j++) {
                    if (j == 0) {
                        value = rs.getString("Username");
                    } else {
                       value = rs.getString("Email");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++;
            }
                
        } catch(Exception e) {
            System.out.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_atlanta_zoo3 = new java.awt.Label();
        text_view_vstaff = new java.awt.Label();
        jButton_delete_staff_member = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButton_home = new javax.swing.JButton();
        jButton_username_up = new javax.swing.JButton();
        jButton_username_down = new javax.swing.JButton();
        jButton_email_up = new javax.swing.JButton();
        jButton_email_down = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        text_atlanta_zoo3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        text_atlanta_zoo3.setName(""); // NOI18N
        text_atlanta_zoo3.setText("Atlanta Zoo");

        text_view_vstaff.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        text_view_vstaff.setName(""); // NOI18N
        text_view_vstaff.setText("View Staff");

        jButton_delete_staff_member.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_delete_staff_member.setText("Delete Staff Member");
        jButton_delete_staff_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delete_staff_memberActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        jButton_home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_home.setText("Home");
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });

        jButton_username_up.setBackground(new java.awt.Color(255, 255, 255));
        jButton_username_up.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_username_up.setText("▲");
        jButton_username_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_username_upActionPerformed(evt);
            }
        });

        jButton_username_down.setBackground(new java.awt.Color(255, 255, 255));
        jButton_username_down.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_username_down.setText("▼");
        jButton_username_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_username_downActionPerformed(evt);
            }
        });

        jButton_email_up.setBackground(new java.awt.Color(255, 255, 255));
        jButton_email_up.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_email_up.setText("▲");
        jButton_email_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_email_upActionPerformed(evt);
            }
        });

        jButton_email_down.setBackground(new java.awt.Color(255, 255, 255));
        jButton_email_down.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_email_down.setText("▼");
        jButton_email_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_email_downActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton_delete_staff_member)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_home)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(text_atlanta_zoo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(text_view_vstaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton_username_up)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_username_down)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_email_up)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_email_down)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_atlanta_zoo3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_view_vstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_username_down)
                            .addComponent(jButton_username_up)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_email_down)
                            .addComponent(jButton_email_up))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_delete_staff_member)
                    .addComponent(jButton_home))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_delete_staff_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delete_staff_memberActionPerformed
        int[] rows = jTable.getSelectedRows();
        int i = 0;
        String userName;
        Admin_View_Staff ex;
        while (i < rows.length) {
            userName = (String)jTable.getModel().getValueAt(rows[i],0);
            Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                Statement myStmt = null;
                ResultSet myRs = null;
                myStmt = con.createStatement();
                String query = " delete from Users where Username = ?";

                // create the mysql insert preparedstatement
                PreparedStatement preparedStmt = con.prepareStatement(query);
                preparedStmt.setString (1, userName);
                // execute the preparedstatement
                preparedStmt.execute();
            } catch(Exception e) {
                System.err.println("Exception: " + e.getMessage());
            } finally {
                try {
                    if(con != null)
                    con.close();
                } catch(SQLException e) {}
            } 
            i++;
        }
        ex = new Admin_View_Staff();
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_delete_staff_memberActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        Admin_Main main = new Admin_Main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jButton_username_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_username_upActionPerformed
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
            "cs4400_group8",
            "l5sU95me");
            PreparedStatement stmt = null;
            String sql = "select * from Users where Role = ? ORDER BY Username ASC";
            stmt = con.prepareStatement(sql);
            stmt.setString(1, "Staff");
            ResultSet rs = stmt.executeQuery();
            int i = 0;
            String value;
            while (rs.next()) {
                for (int j = 0; j < 2; j++) {
                    if (j == 0) {
                        value = rs.getString("Username");
                    } else {
                       value = rs.getString("Email");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++;
            }
                
        } catch(Exception e) {
            System.out.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        } 
    }//GEN-LAST:event_jButton_username_upActionPerformed

    private void jButton_username_downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_username_downActionPerformed
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
            "cs4400_group8",
            "l5sU95me");
            PreparedStatement stmt = null;
            String sql = "select * from Users where Role = ? ORDER BY Username DESC";
            stmt = con.prepareStatement(sql);
            stmt.setString(1, "Staff");
            ResultSet rs = stmt.executeQuery();
            int i = 0;
            String value;
            while (rs.next()) {
                for (int j = 0; j < 2; j++) {
                    if (j == 0) {
                        value = rs.getString("Username");
                    } else {
                       value = rs.getString("Email");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++;
            }
                
        } catch(Exception e) {
            System.out.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        } 
    }//GEN-LAST:event_jButton_username_downActionPerformed

    private void jButton_email_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_email_upActionPerformed
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
            "cs4400_group8",
            "l5sU95me");
            PreparedStatement stmt = null;
            String sql = "select * from Users where Role = ? ORDER BY Email ASC";
            stmt = con.prepareStatement(sql);
            stmt.setString(1, "Staff");
            ResultSet rs = stmt.executeQuery();
            int i = 0;
            String value;
            while (rs.next()) {
                for (int j = 0; j < 2; j++) {
                    if (j == 0) {
                        value = rs.getString("Username");
                    } else {
                       value = rs.getString("Email");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++;
            }
                
        } catch(Exception e) {
            System.out.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        } 
    }//GEN-LAST:event_jButton_email_upActionPerformed

    private void jButton_email_downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_email_downActionPerformed
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
            "cs4400_group8",
            "l5sU95me");
            PreparedStatement stmt = null;
            String sql = "select * from Users where Role = ? ORDER BY Email DESC";
            stmt = con.prepareStatement(sql);
            stmt.setString(1, "Staff");
            ResultSet rs = stmt.executeQuery();
            int i = 0;
            String value;
            while (rs.next()) {
                for (int j = 0; j < 2; j++) {
                    if (j == 0) {
                        value = rs.getString("Username");
                    } else {
                       value = rs.getString("Email");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++;
            }
                
        } catch(Exception e) {
            System.out.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        } 
    }//GEN-LAST:event_jButton_email_downActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_View_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_View_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_View_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_View_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_View_Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_delete_staff_member;
    private javax.swing.JButton jButton_email_down;
    private javax.swing.JButton jButton_email_up;
    private javax.swing.JButton jButton_home;
    private javax.swing.JButton jButton_username_down;
    private javax.swing.JButton jButton_username_up;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private java.awt.Label text_atlanta_zoo3;
    private java.awt.Label text_view_vstaff;
    // End of variables declaration//GEN-END:variables
}
