
import java.awt.event.WindowEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gresh
 */
public class Staff_Main extends javax.swing.JFrame {
    private String staffUsername;
    /**
     * Creates new form Staff_Main
     */
    public Staff_Main(String username) {
        initComponents();
        this.staffUsername = username;
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_search_for_animals = new javax.swing.JButton();
        jButton_logout = new javax.swing.JButton();
        text_atlanta_zoo3 = new java.awt.Label();
        jButton_view_shows = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jButton_search_for_animals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_search_for_animals.setText("Search For Animals");
        jButton_search_for_animals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_search_for_animalsMouseClicked(evt);
            }
        });
        jButton_search_for_animals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_search_for_animalsActionPerformed(evt);
            }
        });

        jButton_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_logout.setText("Logout");
        jButton_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_logoutMouseClicked(evt);
            }
        });
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        text_atlanta_zoo3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        text_atlanta_zoo3.setName(""); // NOI18N
        text_atlanta_zoo3.setText("Atlanta Zoo");

        jButton_view_shows.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_view_shows.setText("View Shows");
        jButton_view_shows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_view_showsMouseClicked(evt);
            }
        });
        jButton_view_shows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_view_showsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(text_atlanta_zoo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(492, 492, 492)
                        .addComponent(jButton_logout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton_search_for_animals)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_view_shows)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_atlanta_zoo3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_search_for_animals)
                    .addComponent(jButton_view_shows))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jButton_logout)
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_logoutActionPerformed

    private void jButton_view_showsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_view_showsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_view_showsActionPerformed

    private void jButton_search_for_animalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_search_for_animalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_search_for_animalsActionPerformed

    private void jButton_search_for_animalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_search_for_animalsMouseClicked
        Visitor_Search_For_Animals ex = new Visitor_Search_For_Animals(true, staffUsername);
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_search_for_animalsMouseClicked

    private void jButton_view_showsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_view_showsMouseClicked
        Staff_Shows ex = new Staff_Shows(staffUsername);
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_view_showsMouseClicked

    private void jButton_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_logoutMouseClicked
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff_Main("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_search_for_animals;
    private javax.swing.JButton jButton_view_shows;
    private java.awt.Label text_atlanta_zoo3;
    // End of variables declaration//GEN-END:variables
}
