
import java.awt.event.WindowEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gresh
 */
public class Visitor_Main extends javax.swing.JFrame {
    private String userEmail;
    /**
     * Creates new form Visitor_Main
     */
    public Visitor_Main(String email) {
        initComponents();
        this.userEmail = email;
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_atlanta_zoo3 = new java.awt.Label();
        jButton_view_exhibit_history = new javax.swing.JButton();
        jButton_search_shows = new javax.swing.JButton();
        jButton_view_show_history = new javax.swing.JButton();
        jButton_search_for_animals = new javax.swing.JButton();
        jButton_logout = new javax.swing.JButton();
        jButton_search_exhibits = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        text_atlanta_zoo3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        text_atlanta_zoo3.setName(""); // NOI18N
        text_atlanta_zoo3.setText("Atlanta Zoo");

        jButton_view_exhibit_history.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_view_exhibit_history.setText("View Exhibit History");
        jButton_view_exhibit_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_view_exhibit_historyMouseClicked(evt);
            }
        });

        jButton_search_shows.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_search_shows.setText("Search Shows");
        jButton_search_shows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_search_showsMouseClicked(evt);
            }
        });
        jButton_search_shows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_search_showsActionPerformed(evt);
            }
        });

        jButton_view_show_history.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_view_show_history.setText("View Show History");
        jButton_view_show_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_view_show_historyMouseClicked(evt);
            }
        });
        jButton_view_show_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_view_show_historyActionPerformed(evt);
            }
        });

        jButton_search_for_animals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_search_for_animals.setText("Search For Animals");
        jButton_search_for_animals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_search_for_animalsMouseClicked(evt);
            }
        });
        jButton_search_for_animals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_search_for_animalsActionPerformed(evt);
            }
        });

        jButton_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_logout.setText("Logout");
        jButton_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_logoutMouseClicked(evt);
            }
        });
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        jButton_search_exhibits.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_search_exhibits.setText("Search Exhibits");
        jButton_search_exhibits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_search_exhibitsMouseClicked(evt);
            }
        });
        jButton_search_exhibits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_search_exhibitsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_search_exhibits)
                            .addComponent(jButton_search_shows))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_view_exhibit_history)
                            .addComponent(jButton_view_show_history)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_search_for_animals)
                        .addGap(99, 99, 99)
                        .addComponent(jButton_logout)))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(text_atlanta_zoo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_atlanta_zoo3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_view_exhibit_history)
                    .addComponent(jButton_search_exhibits))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_search_shows)
                    .addComponent(jButton_view_show_history))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_search_for_animals)
                    .addComponent(jButton_logout))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_search_showsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_search_showsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_search_showsActionPerformed

    private void jButton_view_show_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_view_show_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_view_show_historyActionPerformed

    private void jButton_search_for_animalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_search_for_animalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_search_for_animalsActionPerformed

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_logoutActionPerformed

    private void jButton_search_exhibitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_search_exhibitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_search_exhibitsActionPerformed

    private void jButton_search_exhibitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_search_exhibitsMouseClicked
        Visitor_Search_For_Exhibits ex = new Visitor_Search_For_Exhibits(userEmail);
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_search_exhibitsMouseClicked

    private void jButton_view_exhibit_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_view_exhibit_historyMouseClicked
        Visitor_Exhibit_History ex = new Visitor_Exhibit_History(userEmail);
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_view_exhibit_historyMouseClicked

    private void jButton_search_showsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_search_showsMouseClicked
        Visitor_Search_For_Shows ex = new Visitor_Search_For_Shows(userEmail);
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_search_showsMouseClicked

    private void jButton_view_show_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_view_show_historyMouseClicked
        Visitor_Show_History ex = new Visitor_Show_History(userEmail);
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_view_show_historyMouseClicked

    private void jButton_search_for_animalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_search_for_animalsMouseClicked
        Visitor_Search_For_Animals ex = new Visitor_Search_For_Animals(userEmail);
        ex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_search_for_animalsMouseClicked

    private void jButton_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_logoutMouseClicked
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visitor_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visitor_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visitor_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visitor_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visitor_Main("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_search_exhibits;
    private javax.swing.JButton jButton_search_for_animals;
    private javax.swing.JButton jButton_search_shows;
    private javax.swing.JButton jButton_view_exhibit_history;
    private javax.swing.JButton jButton_view_show_history;
    private java.awt.Label text_atlanta_zoo3;
    // End of variables declaration//GEN-END:variables
}
