
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gresh
 */
public class Visitor_Search_For_Shows extends javax.swing.JFrame {
    boolean isStaff;
    String userEmail;
    boolean searchPerformed;
    /**
     * Creates new form SearchForShows
     */
    public Visitor_Search_For_Shows(String userEmail) {
        initComponents();
        this.isStaff = false;
        this.userEmail = userEmail;
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        fillValues();
    }
    public Visitor_Search_For_Shows(boolean b, String userEmail) {
        initComponents();
        this.isStaff = b;
        this.userEmail = userEmail;
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        fillValues();
    }
    
    public void fillValues() {
        Connection con = null;
        try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM `Shows`";
                
                stmt = con.prepareStatement(sql);
                
                
                
                ResultSet myRs = stmt.executeQuery();
            //clear table
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                System.out.println("Values Found");
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = myRs.getString("Name");
                    } else if (j == 1) {
                        value = myRs.getString("ExhibitName");
                    } else {
                        value = myRs.getObject("ShowTime");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++; //move to next result
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_atlanta_zoo = new java.awt.Label();
        text_shows = new java.awt.Label();
        jButton_search = new javax.swing.JButton();
        text_name = new java.awt.Label();
        jTextField_name = new javax.swing.JTextField();
        text_species = new java.awt.Label();
        text_date = new java.awt.Label();
        jComboBox_exhibit = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButton_log_visit = new javax.swing.JButton();
        jCalendar_date = new com.toedter.calendar.JCalendar();
        jButton_home = new javax.swing.JButton();
        jCheckBox_date = new javax.swing.JCheckBox();
        jCheckBox_name = new javax.swing.JCheckBox();
        jCheckBox_exhibit = new javax.swing.JCheckBox();
        jButton_name_up = new javax.swing.JButton();
        jButton_name_down = new javax.swing.JButton();
        jButton_exhibit_up = new javax.swing.JButton();
        jButton_exhibit_down = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        text_atlanta_zoo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        text_atlanta_zoo.setName(""); // NOI18N
        text_atlanta_zoo.setText("Atlanta Zoo");

        text_shows.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        text_shows.setName(""); // NOI18N
        text_shows.setText("Shows");

        jButton_search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_search.setText("Search");
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        text_name.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        text_name.setText("Name");

        text_species.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        text_species.setText("Exhibit");

        text_date.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        text_date.setText("Date");

        jComboBox_exhibit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pacific", "Jungle", "Sahara", "Mountainous", "Birds" }));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Exhibit", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        jButton_log_visit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_log_visit.setText("Log Visit");
        jButton_log_visit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_log_visitActionPerformed(evt);
            }
        });

        jButton_home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_home.setText("Home");
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });

        jButton_name_up.setBackground(new java.awt.Color(255, 255, 255));
        jButton_name_up.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_name_up.setText("▲");
        jButton_name_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_name_upActionPerformed(evt);
            }
        });

        jButton_name_down.setBackground(new java.awt.Color(255, 255, 255));
        jButton_name_down.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_name_down.setText("▼");
        jButton_name_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_name_downActionPerformed(evt);
            }
        });

        jButton_exhibit_up.setBackground(new java.awt.Color(255, 255, 255));
        jButton_exhibit_up.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_exhibit_up.setText("▲");
        jButton_exhibit_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exhibit_upActionPerformed(evt);
            }
        });

        jButton_exhibit_down.setBackground(new java.awt.Color(255, 255, 255));
        jButton_exhibit_down.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_exhibit_down.setText("▼");
        jButton_exhibit_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exhibit_downActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(text_atlanta_zoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(text_shows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jButton_search)
                        .addGap(176, 176, 176)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox_name)
                            .addComponent(jCheckBox_exhibit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_species, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(232, 232, 232)
                                        .addComponent(jCheckBox_date)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox_exhibit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCalendar_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_log_visit)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jButton_name_up)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_name_down)
                                .addGap(101, 101, 101)
                                .addComponent(jButton_exhibit_up)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_exhibit_down))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_home)
                                .addGap(23, 23, 23)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(text_atlanta_zoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_search)
                            .addComponent(text_shows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_name)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_species, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_exhibit)
                            .addComponent(jComboBox_exhibit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_date)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCalendar_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton_log_visit)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_name_up)
                            .addComponent(jButton_name_down)
                            .addComponent(jButton_exhibit_up)
                            .addComponent(jButton_exhibit_down))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jButton_home)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        
        boolean search_name = jCheckBox_name.isSelected();
        boolean search_exhibit = jCheckBox_exhibit.isSelected();
        boolean search_date = jCheckBox_date.isSelected();
        int name_pos = -1;
        int exhibit_pos = -1;
        int date_pos = -1;
        int numColumns = 1;
        String name = new String(jTextField_name.getText());
        String exhibit = "" + jComboBox_exhibit.getSelectedItem();
        
        Date dateTemp = jCalendar_date.getDate();
        Date date = new Date(dateTemp.getYear(), dateTemp.getMonth(), dateTemp.getDate());
        System.out.println(date);
        if (!search_name && !search_exhibit && !search_date){
            JOptionPane.showMessageDialog(null, "Must check a search preference box");

        } else {
            Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM `Shows` WHERE ";
                if (search_name) {
                    name_pos = numColumns;
                    numColumns++;
                    sql += "Name = ? AND ";
                }
                if (search_date) {
                    date_pos = numColumns;
                    numColumns++;
                    sql += "DATE(ShowTime) = ? AND ";
                }
                if (search_exhibit) {
                    exhibit_pos = numColumns;
                    numColumns++;
                    sql += "ExhibitName = ? AND ";
                }
                //get rid of last AND
                sql = sql.substring(0, sql.length() - 5);
                stmt = con.prepareStatement(sql);
                if (search_name) {
                    stmt.setString(name_pos, name);
                }
                if (search_date) {
                    stmt.setObject(date_pos, date);
                }
                if (search_exhibit) {
                    stmt.setString(exhibit_pos, exhibit);
                }
                
                
                ResultSet myRs = stmt.executeQuery();
                searchPerformed = true;
            //clear table
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                System.out.println("Values Found");
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = myRs.getString("Name");
                    } else if (j == 1) {
                        value = myRs.getString("ExhibitName");
                    } else {
                        value = myRs.getObject("ShowTime");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++; //move to next result
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }   
        }
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jButton_log_visitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_log_visitActionPerformed
        int[] rows = jTable.getSelectedRows();
        int i = 0;
        String name;
        Date date;
        Date current_date = new Date();
        while (i < rows.length) {
            name = (String)jTable.getModel().getValueAt(rows[i],0);
            date = (Date)jTable.getModel().getValueAt(rows[i], 2);
            i++;
            Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt = null;
                String sql = "insert into ShowVisits (ShowName, ShowTime, Visitor)"
                + " values (?, ?, ?)";
                stmt = con.prepareStatement(sql);
                stmt.setString(1, name);
                stmt.setObject(2, date);
                stmt.setObject(3, userEmail);
                if (!date.after(current_date)) {
                    stmt.execute();
                } else {
                    JOptionPane.showMessageDialog(null, "Cannot log a visit to a show in the future");
                }

            } catch(Exception e) {
                System.out.println("Exception: " + e.getMessage());
            } finally {
                try {
                    if(con != null)
                    con.close();
                } catch(SQLException e) {}
            } 
        }
    }//GEN-LAST:event_jButton_log_visitActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        Visitor_Main main = new Visitor_Main(userEmail);
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jButton_name_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_name_upActionPerformed
        if (searchPerformed) {
        boolean search_name = jCheckBox_name.isSelected();
        boolean search_exhibit = jCheckBox_exhibit.isSelected();
        boolean search_date = jCheckBox_date.isSelected();
        int name_pos = -1;
        int exhibit_pos = -1;
        int date_pos = -1;
        int numColumns = 1;
        String name = new String(jTextField_name.getText());
        String exhibit = "" + jComboBox_exhibit.getSelectedItem();
        
        Date dateTemp = jCalendar_date.getDate();
        Date date = new Date(dateTemp.getYear(), dateTemp.getMonth(), dateTemp.getDate());
        //System.out.println(date);
        if (!search_name && !search_exhibit && !search_date){
            JOptionPane.showMessageDialog(null, "Must check a search preference box");

        } else {
            Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM `Shows` WHERE ";
                if (search_name) {
                    name_pos = numColumns;
                    numColumns++;
                    sql += "Name = ? AND ";
                }
                if (search_date) {
                    date_pos = numColumns;
                    numColumns++;
                    sql += "DATE(ShowTime) = ? AND ";
                }
                if (search_exhibit) {
                    exhibit_pos = numColumns;
                    numColumns++;
                    sql += "ExhibitName = ? AND ";
                }
                //get rid of last AND
                sql = sql.substring(0, sql.length() - 5);
                sql += "ORDER BY Name ASC";
                stmt = con.prepareStatement(sql);
                if (search_name) {
                    stmt.setString(name_pos, name);
                }
                if (search_date) {
                    stmt.setObject(date_pos, date);
                }
                if (search_exhibit) {
                    stmt.setString(exhibit_pos, exhibit);
                }
                
                
                ResultSet myRs = stmt.executeQuery();
            //clear table
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                System.out.println("Values Found");
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = myRs.getString("Name");
                    } else if (j == 1) {
                        value = myRs.getString("ExhibitName");
                    } else {
                        value = myRs.getObject("ShowTime");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++; //move to next result
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }   
        }
        } else {
            Connection con = null;
        try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM `Shows` ORDER BY Name ASC";
                
                stmt = con.prepareStatement(sql);
                
                
                
                ResultSet myRs = stmt.executeQuery();
            //clear table
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                System.out.println("Values Found");
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = myRs.getString("Name");
                    } else if (j == 1) {
                        value = myRs.getString("ExhibitName");
                    } else {
                        value = myRs.getObject("ShowTime");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++; //move to next result
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }   
        }
    }//GEN-LAST:event_jButton_name_upActionPerformed

    private void jButton_name_downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_name_downActionPerformed
        if (searchPerformed) {
        boolean search_name = jCheckBox_name.isSelected();
        boolean search_exhibit = jCheckBox_exhibit.isSelected();
        boolean search_date = jCheckBox_date.isSelected();
        int name_pos = -1;
        int exhibit_pos = -1;
        int date_pos = -1;
        int numColumns = 1;
        String name = new String(jTextField_name.getText());
        String exhibit = "" + jComboBox_exhibit.getSelectedItem();
        
        Date dateTemp = jCalendar_date.getDate();
        Date date = new Date(dateTemp.getYear(), dateTemp.getMonth(), dateTemp.getDate());
        //System.out.println(date);
        if (!search_name && !search_exhibit && !search_date){
            JOptionPane.showMessageDialog(null, "Must check a search preference box");

        } else {
            Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM `Shows` WHERE ";
                if (search_name) {
                    name_pos = numColumns;
                    numColumns++;
                    sql += "Name = ? AND ";
                }
                if (search_date) {
                    date_pos = numColumns;
                    numColumns++;
                    sql += "DATE(ShowTime) = ? AND ";
                }
                if (search_exhibit) {
                    exhibit_pos = numColumns;
                    numColumns++;
                    sql += "ExhibitName = ? AND ";
                }
                //get rid of last AND
                sql = sql.substring(0, sql.length() - 5);
                sql += "ORDER BY Name DESC";
                stmt = con.prepareStatement(sql);
                if (search_name) {
                    stmt.setString(name_pos, name);
                }
                if (search_date) {
                    stmt.setObject(date_pos, date);
                }
                if (search_exhibit) {
                    stmt.setString(exhibit_pos, exhibit);
                }
                
                
                ResultSet myRs = stmt.executeQuery();
            //clear table
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                System.out.println("Values Found");
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = myRs.getString("Name");
                    } else if (j == 1) {
                        value = myRs.getString("ExhibitName");
                    } else {
                        value = myRs.getObject("ShowTime");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++; //move to next result
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }   
        }
        } else {
            Connection con = null;
        try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM `Shows` ORDER BY Name DESC";
                
                stmt = con.prepareStatement(sql);
                
                
                
                ResultSet myRs = stmt.executeQuery();
            //clear table
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                System.out.println("Values Found");
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = myRs.getString("Name");
                    } else if (j == 1) {
                        value = myRs.getString("ExhibitName");
                    } else {
                        value = myRs.getObject("ShowTime");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++; //move to next result
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }   
        }
    }//GEN-LAST:event_jButton_name_downActionPerformed

    private void jButton_exhibit_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exhibit_upActionPerformed
        if (searchPerformed) {
        boolean search_name = jCheckBox_name.isSelected();
        boolean search_exhibit = jCheckBox_exhibit.isSelected();
        boolean search_date = jCheckBox_date.isSelected();
        int name_pos = -1;
        int exhibit_pos = -1;
        int date_pos = -1;
        int numColumns = 1;
        String name = new String(jTextField_name.getText());
        String exhibit = "" + jComboBox_exhibit.getSelectedItem();
        
        Date dateTemp = jCalendar_date.getDate();
        Date date = new Date(dateTemp.getYear(), dateTemp.getMonth(), dateTemp.getDate());
        //System.out.println(date);
        if (!search_name && !search_exhibit && !search_date){
            JOptionPane.showMessageDialog(null, "Must check a search preference box");

        } else {
            Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM `Shows` WHERE ";
                if (search_name) {
                    name_pos = numColumns;
                    numColumns++;
                    sql += "Name = ? AND ";
                }
                if (search_date) {
                    date_pos = numColumns;
                    numColumns++;
                    sql += "DATE(ShowTime) = ? AND ";
                }
                if (search_exhibit) {
                    exhibit_pos = numColumns;
                    numColumns++;
                    sql += "ExhibitName = ? AND ";
                }
                //get rid of last AND
                sql = sql.substring(0, sql.length() - 5);
                sql += "ORDER BY ExhibitName ASC";
                stmt = con.prepareStatement(sql);
                if (search_name) {
                    stmt.setString(name_pos, name);
                }
                if (search_date) {
                    stmt.setObject(date_pos, date);
                }
                if (search_exhibit) {
                    stmt.setString(exhibit_pos, exhibit);
                }
                
                
                ResultSet myRs = stmt.executeQuery();
            //clear table
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                System.out.println("Values Found");
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = myRs.getString("Name");
                    } else if (j == 1) {
                        value = myRs.getString("ExhibitName");
                    } else {
                        value = myRs.getObject("ShowTime");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++; //move to next result
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }   
        }
        } else {
            Connection con = null;
        try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM `Shows` ORDER BY ExhibitName ASC";
                
                stmt = con.prepareStatement(sql);
                
                
                
                ResultSet myRs = stmt.executeQuery();
            //clear table
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                System.out.println("Values Found");
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = myRs.getString("Name");
                    } else if (j == 1) {
                        value = myRs.getString("ExhibitName");
                    } else {
                        value = myRs.getObject("ShowTime");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++; //move to next result
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }   
        }
    }//GEN-LAST:event_jButton_exhibit_upActionPerformed

    private void jButton_exhibit_downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exhibit_downActionPerformed
        if (searchPerformed) {
        boolean search_name = jCheckBox_name.isSelected();
        boolean search_exhibit = jCheckBox_exhibit.isSelected();
        boolean search_date = jCheckBox_date.isSelected();
        int name_pos = -1;
        int exhibit_pos = -1;
        int date_pos = -1;
        int numColumns = 1;
        String name = new String(jTextField_name.getText());
        String exhibit = "" + jComboBox_exhibit.getSelectedItem();
        
        Date dateTemp = jCalendar_date.getDate();
        Date date = new Date(dateTemp.getYear(), dateTemp.getMonth(), dateTemp.getDate());
        //System.out.println(date);
        if (!search_name && !search_exhibit && !search_date){
            JOptionPane.showMessageDialog(null, "Must check a search preference box");

        } else {
            Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM `Shows` WHERE ";
                if (search_name) {
                    name_pos = numColumns;
                    numColumns++;
                    sql += "Name = ? AND ";
                }
                if (search_date) {
                    date_pos = numColumns;
                    numColumns++;
                    sql += "DATE(ShowTime) = ? AND ";
                }
                if (search_exhibit) {
                    exhibit_pos = numColumns;
                    numColumns++;
                    sql += "ExhibitName = ? AND ";
                }
                //get rid of last AND
                sql = sql.substring(0, sql.length() - 5);
                sql += "ORDER BY ExhibitName DESC";
                stmt = con.prepareStatement(sql);
                if (search_name) {
                    stmt.setString(name_pos, name);
                }
                if (search_date) {
                    stmt.setObject(date_pos, date);
                }
                if (search_exhibit) {
                    stmt.setString(exhibit_pos, exhibit);
                }
                
                
                ResultSet myRs = stmt.executeQuery();
            //clear table
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                System.out.println("Values Found");
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = myRs.getString("Name");
                    } else if (j == 1) {
                        value = myRs.getString("ExhibitName");
                    } else {
                        value = myRs.getObject("ShowTime");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++; //move to next result
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }   
        }
        } else {
            Connection con = null;
        try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM `Shows` ORDER BY ExhibitName DESC";
                
                stmt = con.prepareStatement(sql);
                
                
                
                ResultSet myRs = stmt.executeQuery();
            //clear table
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                System.out.println("Values Found");
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = myRs.getString("Name");
                    } else if (j == 1) {
                        value = myRs.getString("ExhibitName");
                    } else {
                        value = myRs.getObject("ShowTime");
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++; //move to next result
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }   
        }
    }//GEN-LAST:event_jButton_exhibit_downActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visitor_Search_For_Shows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visitor_Search_For_Shows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visitor_Search_For_Shows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visitor_Search_For_Shows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visitor_Search_For_Shows("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_exhibit_down;
    private javax.swing.JButton jButton_exhibit_up;
    private javax.swing.JButton jButton_home;
    private javax.swing.JButton jButton_log_visit;
    private javax.swing.JButton jButton_name_down;
    private javax.swing.JButton jButton_name_up;
    private javax.swing.JButton jButton_search;
    private com.toedter.calendar.JCalendar jCalendar_date;
    private javax.swing.JCheckBox jCheckBox_date;
    private javax.swing.JCheckBox jCheckBox_exhibit;
    private javax.swing.JCheckBox jCheckBox_name;
    private javax.swing.JComboBox<String> jComboBox_exhibit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField_name;
    private java.awt.Label text_atlanta_zoo;
    private java.awt.Label text_date;
    private java.awt.Label text_name;
    private java.awt.Label text_shows;
    private java.awt.Label text_species;
    // End of variables declaration//GEN-END:variables
}
