
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gresh
 */
public class Visitor_Show_History extends javax.swing.JFrame {
    private String userEmail;
    private boolean searchPerformed;
    /**
     * Creates new form Show_History
     */
    public Visitor_Show_History(String userEmail) {
        initComponents();
        this.userEmail = userEmail;
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        fillValues();
    }
     public void fillValues() {
        //fill text boxes
        //System.out.println("FILLING VALUES");
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
            "cs4400_group8",
            "l5sU95me");
            PreparedStatement stmt = null;
            String sql = "SELECT * FROM ShowVisits WHERE Visitor = ?";
            stmt = con.prepareStatement(sql);
            stmt.setString(1, userEmail);
            ResultSet rs = stmt.executeQuery();
            int i = 0;
            Object value;
            while (rs.next()) {
                PreparedStatement showStmt = null;
                String showSql = "select ExhibitName from `Shows` where Name = ? and ShowTime = ?";
                showStmt = con.prepareStatement(showSql);
                showStmt.setString(1, rs.getString("ShowName"));
                showStmt.setObject(2, rs.getObject("ShowTime"));
                ResultSet showRs = showStmt.executeQuery();
                showRs.next();
                String exhibit = showRs.getString(1);
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = rs.getString("ShowName");
                    } else if (j == 1) {
                       value = rs.getObject("ShowTime");
                    } else {
                        value = exhibit;
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++;
            }
                
        } catch(Exception e) {
            System.out.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_atlanta_zoo1 = new java.awt.Label();
        text_show_history = new java.awt.Label();
        jButton1_search = new javax.swing.JButton();
        text_name3 = new java.awt.Label();
        jTextField_name = new javax.swing.JTextField();
        text_time = new java.awt.Label();
        text_exhibit = new java.awt.Label();
        jComboBox_exhibit = new javax.swing.JComboBox<>();
        jButton_home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jCheckBox_exhibit = new javax.swing.JCheckBox();
        jCheckBox_name = new javax.swing.JCheckBox();
        jCheckBox_date = new javax.swing.JCheckBox();
        jButton_name_up = new javax.swing.JButton();
        jButton_name_down = new javax.swing.JButton();
        jButton_time_up = new javax.swing.JButton();
        jButton_time_down = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        text_atlanta_zoo1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        text_atlanta_zoo1.setName(""); // NOI18N
        text_atlanta_zoo1.setText("Atlanta Zoo");

        text_show_history.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        text_show_history.setName(""); // NOI18N
        text_show_history.setText("Show History");

        jButton1_search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1_search.setText("Search");
        jButton1_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_searchActionPerformed(evt);
            }
        });

        text_name3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        text_name3.setText("Name");

        text_time.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        text_time.setText("Date");

        text_exhibit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        text_exhibit.setText("Exhibit");

        jComboBox_exhibit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pacific", "Jungle", "Sahara", "Mountainous", "Birds" }));

        jButton_home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_home.setText("Home");
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Time", "Exhibit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        jButton_name_up.setBackground(new java.awt.Color(255, 255, 255));
        jButton_name_up.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_name_up.setText("▲");
        jButton_name_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_name_upActionPerformed(evt);
            }
        });

        jButton_name_down.setBackground(new java.awt.Color(255, 255, 255));
        jButton_name_down.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_name_down.setText("▼");
        jButton_name_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_name_downActionPerformed(evt);
            }
        });

        jButton_time_up.setBackground(new java.awt.Color(255, 255, 255));
        jButton_time_up.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_time_up.setText("▲");
        jButton_time_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_time_upActionPerformed(evt);
            }
        });

        jButton_time_down.setBackground(new java.awt.Color(255, 255, 255));
        jButton_time_down.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton_time_down.setText("▼");
        jButton_time_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_time_downActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(text_atlanta_zoo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(text_show_history, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1_search)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_home)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBox_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBox_exhibit)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(text_name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(text_exhibit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox_exhibit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(49, 49, 49)
                                        .addComponent(jCheckBox_date))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jButton_name_up)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton_name_down)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_time_up)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton_time_down)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton1_search))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_atlanta_zoo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_show_history, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(text_name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox_name)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox_date)
                                    .addComponent(text_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCheckBox_exhibit)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jComboBox_exhibit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(text_exhibit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_name_down, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_name_up, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_time_down, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_time_up, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_home)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_searchActionPerformed
        boolean search_name = jCheckBox_name.isSelected();
        boolean search_exhibit = jCheckBox_exhibit.isSelected();
        boolean search_date = jCheckBox_date.isSelected();
        int name_pos = -1;
        int exhibit_pos = -1;
        int date_pos = -1;
        int numColumns = 2;
        String name = new String(jTextField_name.getText());
        String exhibit = "" + jComboBox_exhibit.getSelectedItem();
        Date dateTemp = jCalendar1.getDate();
        Date date = new Date(dateTemp.getYear(), dateTemp.getMonth(), dateTemp.getDate());
        //parameters
            
        if (!search_name && !search_exhibit && !search_date){
            JOptionPane.showMessageDialog(null, "Must check a search preference box");

        } else {
            Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM ShowVisits WHERE Visitor = ? AND ";
                if (search_name) {
                    name_pos = numColumns;
                    numColumns++;
                    sql += "ShowName = ? AND ";
                }
                if (search_date) {
                    date_pos = numColumns;
                    numColumns++;
                    sql += "DATE(ShowTime) = ? AND ";
                }

                //get rid of last AND
                sql = sql.substring(0, sql.length() - 5);
                stmt = con.prepareStatement(sql);
                
                stmt.setString(1, userEmail);
                if (search_name) {
                    stmt.setString(name_pos, name);
                }
                if (search_date) {
                    stmt.setObject(date_pos, date);
                }
                
                System.out.println(stmt);
                ResultSet myRs = stmt.executeQuery();            //clear table
                System.out.println("EX1");
                searchPerformed = true;
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                PreparedStatement exStmt;
                String exSql = "SELECT ExhibitName FROM Shows WHERE Name = ? AND ShowTime = ?";
                exStmt = con.prepareStatement(exSql);
                exStmt.setString(1, myRs.getString("ShowName"));
                exStmt.setString(2, myRs.getString("ShowTime"));
                ResultSet exRs = exStmt.executeQuery();
                exRs.next();
                String exhibitTemp = exRs.getString(1);
                if (exhibitTemp.equals(exhibit) || !search_exhibit) {
                    for (int j = 0; j < 3; j++) {
                        if (j == 0) {
                            value = myRs.getString("ShowName");
                        } else if (j == 1) {
                            value = myRs.getObject("ShowTime");
                        } else {
                            value = exhibitTemp;
                        }
                        jTable.getModel().setValueAt(value, i, j);
                    }
                    i++; //move to next result
                }
                
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        } 
        }
    }//GEN-LAST:event_jButton1_searchActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        Visitor_Main main = new Visitor_Main(userEmail);
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jButton_name_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_name_upActionPerformed
        if (searchPerformed) {
        boolean search_name = jCheckBox_name.isSelected();
        boolean search_exhibit = jCheckBox_exhibit.isSelected();
        boolean search_date = jCheckBox_date.isSelected();
        int name_pos = -1;
        int exhibit_pos = -1;
        int date_pos = -1;
        int numColumns = 2;
        String name = new String(jTextField_name.getText());
        String exhibit = "" + jComboBox_exhibit.getSelectedItem();
        Date dateTemp = jCalendar1.getDate();
        Date date = new Date(dateTemp.getYear(), dateTemp.getMonth(), dateTemp.getDate());
        //parameters
            
        if (!search_name && !search_exhibit && !search_date){
            JOptionPane.showMessageDialog(null, "Must check a search preference box");

        } else {
            Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM ShowVisits WHERE Visitor = ? AND ";
                if (search_name) {
                    name_pos = numColumns;
                    numColumns++;
                    sql += "ShowName = ? AND ";
                }
                if (search_date) {
                    date_pos = numColumns;
                    numColumns++;
                    sql += "DATE(ShowTime) = ? AND ";
                }

                //get rid of last AND
                sql = sql.substring(0, sql.length() - 5);
                sql += "ORDER BY ShowName ASC";
                stmt = con.prepareStatement(sql);
                
                stmt.setString(1, userEmail);
                if (search_name) {
                    stmt.setString(name_pos, name);
                }
                if (search_date) {
                    stmt.setObject(date_pos, date);
                }
                
                System.out.println(stmt);
                ResultSet myRs = stmt.executeQuery();            //clear table
                System.out.println("EX1");
                searchPerformed = true;
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                PreparedStatement exStmt;
                String exSql = "SELECT ExhibitName FROM Shows WHERE Name = ? AND ShowTime = ?";
                exStmt = con.prepareStatement(exSql);
                exStmt.setString(1, myRs.getString("ShowName"));
                exStmt.setString(2, myRs.getString("ShowTime"));
                ResultSet exRs = exStmt.executeQuery();
                exRs.next();
                String exhibitTemp = exRs.getString(1);
                if (exhibitTemp.equals(exhibit) || !search_exhibit) {
                    for (int j = 0; j < 3; j++) {
                        if (j == 0) {
                            value = myRs.getString("ShowName");
                        } else if (j == 1) {
                            value = myRs.getObject("ShowTime");
                        } else {
                            value = exhibitTemp;
                        }
                        jTable.getModel().setValueAt(value, i, j);
                    }
                    i++; //move to next result
                }
                
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        } 
        }
        } else {
            Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
            "cs4400_group8",
            "l5sU95me");
            PreparedStatement stmt = null;
            String sql = "SELECT * FROM ShowVisits WHERE Visitor = ? ORDER BY ShowName ASC";
            stmt = con.prepareStatement(sql);
            stmt.setString(1, userEmail);
            ResultSet rs = stmt.executeQuery();
            int i = 0;
            Object value;
            while (rs.next()) {
                PreparedStatement showStmt = null;
                String showSql = "select ExhibitName from `Shows` where Name = ? and ShowTime = ?";
                showStmt = con.prepareStatement(showSql);
                showStmt.setString(1, rs.getString("ShowName"));
                showStmt.setObject(2, rs.getObject("ShowTime"));
                ResultSet showRs = showStmt.executeQuery();
                showRs.next();
                String exhibit = showRs.getString(1);
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = rs.getString("ShowName");
                    } else if (j == 1) {
                       value = rs.getObject("ShowTime");
                    } else {
                        value = exhibit;
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++;
            }
                
        } catch(Exception e) {
            System.out.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }
        }
    }//GEN-LAST:event_jButton_name_upActionPerformed

    private void jButton_name_downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_name_downActionPerformed
        if (searchPerformed) {
        boolean search_name = jCheckBox_name.isSelected();
        boolean search_exhibit = jCheckBox_exhibit.isSelected();
        boolean search_date = jCheckBox_date.isSelected();
        int name_pos = -1;
        int exhibit_pos = -1;
        int date_pos = -1;
        int numColumns = 2;
        String name = new String(jTextField_name.getText());
        String exhibit = "" + jComboBox_exhibit.getSelectedItem();
        Date dateTemp = jCalendar1.getDate();
        Date date = new Date(dateTemp.getYear(), dateTemp.getMonth(), dateTemp.getDate());
        //parameters
            
        if (!search_name && !search_exhibit && !search_date){
            JOptionPane.showMessageDialog(null, "Must check a search preference box");

        } else {
            Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM ShowVisits WHERE Visitor = ? AND ";
                if (search_name) {
                    name_pos = numColumns;
                    numColumns++;
                    sql += "ShowName = ? AND ";
                }
                if (search_date) {
                    date_pos = numColumns;
                    numColumns++;
                    sql += "DATE(ShowTime) = ? AND ";
                }

                //get rid of last AND
                sql = sql.substring(0, sql.length() - 5);
                sql += "ORDER BY ShowName DESC";
                stmt = con.prepareStatement(sql);
                
                stmt.setString(1, userEmail);
                if (search_name) {
                    stmt.setString(name_pos, name);
                }
                if (search_date) {
                    stmt.setObject(date_pos, date);
                }
                
                System.out.println(stmt);
                ResultSet myRs = stmt.executeQuery();            //clear table
                System.out.println("EX1");
                searchPerformed = true;
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                PreparedStatement exStmt;
                String exSql = "SELECT ExhibitName FROM Shows WHERE Name = ? AND ShowTime = ?";
                exStmt = con.prepareStatement(exSql);
                exStmt.setString(1, myRs.getString("ShowName"));
                exStmt.setString(2, myRs.getString("ShowTime"));
                ResultSet exRs = exStmt.executeQuery();
                exRs.next();
                String exhibitTemp = exRs.getString(1);
                if (exhibitTemp.equals(exhibit) || !search_exhibit) {
                    for (int j = 0; j < 3; j++) {
                        if (j == 0) {
                            value = myRs.getString("ShowName");
                        } else if (j == 1) {
                            value = myRs.getObject("ShowTime");
                        } else {
                            value = exhibitTemp;
                        }
                        jTable.getModel().setValueAt(value, i, j);
                    }
                    i++; //move to next result
                }
                
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        } 
        }
        } else {
            Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
            "cs4400_group8",
            "l5sU95me");
            PreparedStatement stmt = null;
            String sql = "SELECT * FROM ShowVisits WHERE Visitor = ? ORDER BY ShowName DESC";
            stmt = con.prepareStatement(sql);
            stmt.setString(1, userEmail);
            ResultSet rs = stmt.executeQuery();
            int i = 0;
            Object value;
            while (rs.next()) {
                PreparedStatement showStmt = null;
                String showSql = "select ExhibitName from `Shows` where Name = ? and ShowTime = ?";
                showStmt = con.prepareStatement(showSql);
                showStmt.setString(1, rs.getString("ShowName"));
                showStmt.setObject(2, rs.getObject("ShowTime"));
                ResultSet showRs = showStmt.executeQuery();
                showRs.next();
                String exhibit = showRs.getString(1);
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = rs.getString("ShowName");
                    } else if (j == 1) {
                       value = rs.getObject("ShowTime");
                    } else {
                        value = exhibit;
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++;
            }
                
        } catch(Exception e) {
            System.out.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }
        }
    }//GEN-LAST:event_jButton_name_downActionPerformed

    private void jButton_time_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_time_upActionPerformed
        if (searchPerformed) {
        boolean search_name = jCheckBox_name.isSelected();
        boolean search_exhibit = jCheckBox_exhibit.isSelected();
        boolean search_date = jCheckBox_date.isSelected();
        int name_pos = -1;
        int exhibit_pos = -1;
        int date_pos = -1;
        int numColumns = 2;
        String name = new String(jTextField_name.getText());
        String exhibit = "" + jComboBox_exhibit.getSelectedItem();
        Date dateTemp = jCalendar1.getDate();
        Date date = new Date(dateTemp.getYear(), dateTemp.getMonth(), dateTemp.getDate());
        //parameters
            
        if (!search_name && !search_exhibit && !search_date){
            JOptionPane.showMessageDialog(null, "Must check a search preference box");

        } else {
            Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM ShowVisits WHERE Visitor = ? AND ";
                if (search_name) {
                    name_pos = numColumns;
                    numColumns++;
                    sql += "ShowName = ? AND ";
                }
                if (search_date) {
                    date_pos = numColumns;
                    numColumns++;
                    sql += "DATE(ShowTime) = ? AND ";
                }

                //get rid of last AND
                sql = sql.substring(0, sql.length() - 5);
                sql += "ORDER BY ShowTime ASC";
                stmt = con.prepareStatement(sql);
                
                stmt.setString(1, userEmail);
                if (search_name) {
                    stmt.setString(name_pos, name);
                }
                if (search_date) {
                    stmt.setObject(date_pos, date);
                }
                
                System.out.println(stmt);
                ResultSet myRs = stmt.executeQuery();            //clear table
                System.out.println("EX1");
                searchPerformed = true;
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                PreparedStatement exStmt;
                String exSql = "SELECT ExhibitName FROM Shows WHERE Name = ? AND ShowTime = ?";
                exStmt = con.prepareStatement(exSql);
                exStmt.setString(1, myRs.getString("ShowName"));
                exStmt.setString(2, myRs.getString("ShowTime"));
                ResultSet exRs = exStmt.executeQuery();
                exRs.next();
                String exhibitTemp = exRs.getString(1);
                if (exhibitTemp.equals(exhibit) || !search_exhibit) {
                    for (int j = 0; j < 3; j++) {
                        if (j == 0) {
                            value = myRs.getString("ShowName");
                        } else if (j == 1) {
                            value = myRs.getObject("ShowTime");
                        } else {
                            value = exhibitTemp;
                        }
                        jTable.getModel().setValueAt(value, i, j);
                    }
                    i++; //move to next result
                }
                
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        } 
        }
        } else {
            Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
            "cs4400_group8",
            "l5sU95me");
            PreparedStatement stmt = null;
            String sql = "SELECT * FROM ShowVisits WHERE Visitor = ? ORDER BY ShowTime ASC";
            stmt = con.prepareStatement(sql);
            stmt.setString(1, userEmail);
            ResultSet rs = stmt.executeQuery();
            int i = 0;
            Object value;
            while (rs.next()) {
                PreparedStatement showStmt = null;
                String showSql = "select ExhibitName from `Shows` where Name = ? and ShowTime = ?";
                showStmt = con.prepareStatement(showSql);
                showStmt.setString(1, rs.getString("ShowName"));
                showStmt.setObject(2, rs.getObject("ShowTime"));
                ResultSet showRs = showStmt.executeQuery();
                showRs.next();
                String exhibit = showRs.getString(1);
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = rs.getString("ShowName");
                    } else if (j == 1) {
                       value = rs.getObject("ShowTime");
                    } else {
                        value = exhibit;
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++;
            }
                
        } catch(Exception e) {
            System.out.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }
        }
    }//GEN-LAST:event_jButton_time_upActionPerformed

    private void jButton_time_downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_time_downActionPerformed
       if (searchPerformed) {
        boolean search_name = jCheckBox_name.isSelected();
        boolean search_exhibit = jCheckBox_exhibit.isSelected();
        boolean search_date = jCheckBox_date.isSelected();
        int name_pos = -1;
        int exhibit_pos = -1;
        int date_pos = -1;
        int numColumns = 2;
        String name = new String(jTextField_name.getText());
        String exhibit = "" + jComboBox_exhibit.getSelectedItem();
        Date dateTemp = jCalendar1.getDate();
        Date date = new Date(dateTemp.getYear(), dateTemp.getMonth(), dateTemp.getDate());
        //parameters
            
        if (!search_name && !search_exhibit && !search_date){
            JOptionPane.showMessageDialog(null, "Must check a search preference box");

        } else {
            Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
                "cs4400_group8",
                "l5sU95me");
                PreparedStatement stmt;
                String sql = "SELECT * FROM ShowVisits WHERE Visitor = ? AND ";
                if (search_name) {
                    name_pos = numColumns;
                    numColumns++;
                    sql += "ShowName = ? AND ";
                }
                if (search_date) {
                    date_pos = numColumns;
                    numColumns++;
                    sql += "DATE(ShowTime) = ? AND ";
                }

                //get rid of last AND
                sql = sql.substring(0, sql.length() - 5);
                sql += "ORDER BY ShowTime DExaviSC";
                stmt = con.prepareStatement(sql);
                
                stmt.setString(1, userEmail);
                if (search_name) {
                    stmt.setString(name_pos, name);
                }
                if (search_date) {
                    stmt.setObject(date_pos, date);
                }
                
                System.out.println(stmt);
                ResultSet myRs = stmt.executeQuery();            //clear table
                System.out.println("EX1");
                searchPerformed = true;
            for (int i = 0; i < 25; i++) {
                for (int j = 0; j < 3; j++) {
                    jTable.getModel().setValueAt(null, i, j);   
                }
            }
            int i = 0;
            Object value = null;
            while (myRs.next()) {
                PreparedStatement exStmt;
                String exSql = "SELECT ExhibitName FROM Shows WHERE Name = ? AND ShowTime = ?";
                exStmt = con.prepareStatement(exSql);
                exStmt.setString(1, myRs.getString("ShowName"));
                exStmt.setString(2, myRs.getString("ShowTime"));
                ResultSet exRs = exStmt.executeQuery();
                exRs.next();
                String exhibitTemp = exRs.getString(1);
                if (exhibitTemp.equals(exhibit) || !search_exhibit) {
                    for (int j = 0; j < 3; j++) {
                        if (j == 0) {
                            value = myRs.getString("ShowName");
                        } else if (j == 1) {
                            value = myRs.getObject("ShowTime");
                        } else {
                            value = exhibitTemp;
                        }
                        jTable.getModel().setValueAt(value, i, j);
                    }
                    i++; //move to next result
                }
                
            }
        } catch(Exception e) {
            System.err.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        } 
        }
        } else {
            Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://academic-mysql.cc.gatech.edu/cs4400_group8",
            "cs4400_group8",
            "l5sU95me");
            PreparedStatement stmt = null;
            String sql = "SELECT * FROM ShowVisits WHERE Visitor = ? ORDER BY ShowTime DESC";
            stmt = con.prepareStatement(sql);
            stmt.setString(1, userEmail);
            ResultSet rs = stmt.executeQuery();
            int i = 0;
            Object value;
            while (rs.next()) {
                PreparedStatement showStmt = null;
                String showSql = "select ExhibitName from `Shows` where Name = ? and ShowTime = ?";
                showStmt = con.prepareStatement(showSql);
                showStmt.setString(1, rs.getString("ShowName"));
                showStmt.setObject(2, rs.getObject("ShowTime"));
                ResultSet showRs = showStmt.executeQuery();
                showRs.next();
                String exhibit = showRs.getString(1);
                for (int j = 0; j < 3; j++) {
                    if (j == 0) {
                        value = rs.getString("ShowName");
                    } else if (j == 1) {
                       value = rs.getObject("ShowTime");
                    } else {
                        value = exhibit;
                    }
                    jTable.getModel().setValueAt(value, i, j);
                }
                i++;
            }
                
        } catch(Exception e) {
            System.out.println("Exception: " + e.getMessage());
        } finally {
            try {
                if(con != null)
                con.close();
            } catch(SQLException e) {}
        }
        }
    }//GEN-LAST:event_jButton_time_downActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visitor_Show_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visitor_Show_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visitor_Show_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visitor_Show_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visitor_Show_History("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_search;
    private javax.swing.JButton jButton_home;
    private javax.swing.JButton jButton_name_down;
    private javax.swing.JButton jButton_name_up;
    private javax.swing.JButton jButton_time_down;
    private javax.swing.JButton jButton_time_up;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JCheckBox jCheckBox_date;
    private javax.swing.JCheckBox jCheckBox_exhibit;
    private javax.swing.JCheckBox jCheckBox_name;
    private javax.swing.JComboBox<String> jComboBox_exhibit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField_name;
    private java.awt.Label text_atlanta_zoo1;
    private java.awt.Label text_exhibit;
    private java.awt.Label text_name3;
    private java.awt.Label text_show_history;
    private java.awt.Label text_time;
    // End of variables declaration//GEN-END:variables
}
